# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
z = np.zeros(10)
print(z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: ignored

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
z = np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
z = np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
u = np.eye(3)
print(u)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random((3,3,3))
print(x)

[[[0.34852633 0.31698279 0.94418864]
  [0.19390209 0.77587702 0.73455219]
  [0.05711289 0.85269984 0.91275944]]

 [[0.90956854 0.46082009 0.85857632]
  [0.6826251  0.58882493 0.57075907]
  [0.42765342 0.24325162 0.30373403]]

 [[0.95075368 0.48831157 0.40336381]
  [0.27387486 0.96138169 0.42483809]
  [0.40945928 0.88260408 0.14375337]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
n = np.random.random((10,10))
mn, mx = n.min(), n.max()
print(mn,mx)

0.005362370340041167 0.9731850752333285


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
c = np.random.random(30)
me = c.mean()
print(me)

0.4894513838214615


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
b = np.ones((5,5))

b = np.pad(b, pad_width = 1, mode = 'constant', constant_values=0)
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
v = np.zeros((8,8),dtype= int)
v[1::2,::2]=1
v[::2,1::2]=1
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
v = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
x = (x - np.min(x))/(np.max(x)-np.min(x))
print(x)

[[0.97082499 0.96481032 0.37558939 0.1938958  0.23652572]
 [0.71841718 0.31077538 0.62010706 0.         0.64888928]
 [0.65358913 0.9898869  0.61821748 0.15671544 0.21252299]
 [0.40297877 0.75663055 0.57850463 0.17516515 0.07693758]
 [0.86485704 1.         0.13355751 0.40284005 0.53590671]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
col = np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.ones((5,3)) @ np.ones((3,2))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(11)
x[(3<x)&(x<=8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5) ,-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z**z
2 << z >> 2
z <- z
1j*z
z/1/1
z<z>z

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)),x))

[  1.   3.  10.   4.  10.   5.   2. -10.  -5.  -7.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))

[5 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
x = np.ones(1)/0
_ = np.seterr(**defaults)

with np.errstate(divide = 'ignore'):
  z = np.ones(1)/0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-04-08 2022-04-09 2022-04-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a,b,out = b)
np.divide(a,2,out = a)
np.negative(a,out = a)
np.multiply(a,b,out = a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
c = np.random.uniform(0,10,10)
print(c - c%1)
print(np.floor(c))
print(np.ceil(c)-1)
print(c.astype(int))
print(np.trunc(c))

[3. 2. 0. 4. 0. 2. 1. 4. 0. 6.]
[3. 2. 0. 4. 0. 2. 1. 4. 0. 6.]
[3. 2. 0. 4. 0. 2. 1. 4. 0. 6.]
[3 2 0 4 0 2 1 4 0 6]
[3. 2. 0. 4. 0. 2. 1. 4. 0. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
v = np.zeros((5,5))
v += np.arange(5)
print(v)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for i in range(10):
    yield i

x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

[0.11692416 0.48617717 0.51748587 0.52614026 0.53858849 0.65020568
 0.67854908 0.78246224 0.86910435 0.96564496]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
c = np.arange(10)
np.add.reduce(c)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)
eq = np.array_equal(a,b)
print(eq)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
k = np.zeros(10)
k.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
k = np.random.random((10,2))
x,y = k[:,0],k[:,1]
a = np.sqrt(x**2+y**2)
b = np.arctan2(y,x)
print(a)
print(b)

[0.74643507 0.71867374 0.90329418 0.8262027  0.17181821 0.1866922
 0.47886304 0.72076765 0.19069836 0.80335124]
[0.26751074 1.03318656 0.14151521 1.19669554 1.55911074 0.92941318
 0.76201737 0.03037254 1.36186106 0.03493172]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
x[x.argmax()]=0
print(x)

[0.05575562 0.2912441  0.45031456 0.10609946 0.06112672 0.
 0.08151554 0.42812891 0.15168392 0.08481739]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
k = np.zeros((5,5),[('x',float),('y',float)])
k['x'],k['y']= np.meshgrid(np.linspace(0,1,5),
                           np.linspace(0,1,5))
print(k)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
a = np.arange(8)
b = a + 0.5
c = 1.0/ np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=None)
x = np.zeros((16,16))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(100)
y = np.random.uniform(0,100)
ind = (np.abs(x-y)).argmin()
print(ind)

12


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
l = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(l)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
x = np.random.random((10,2))
a,b = np.atleast_2d(x[:,0],x[:,1])
c = np.sqrt((a-a.T)**2 + (b-b.T)**2)
print(c)

[[0.         0.74891313 0.57149551 0.33612195 0.57806167 0.38971508
  0.50291385 0.54813284 0.61773847 0.90794824]
 [0.74891313 0.         0.26379907 0.89492174 0.60937273 0.87083286
  0.89801615 0.2153994  0.496693   0.82743375]
 [0.57149551 0.26379907 0.         0.80118859 0.65892482 0.80172841
  0.86242035 0.23524691 0.58158885 0.95005988]
 [0.33612195 0.89492174 0.80118859 0.         0.45496685 0.08342745
  0.19901899 0.67999217 0.5554138  0.714479  ]
 [0.57806167 0.60937273 0.65892482 0.45496685 0.         0.38680392
  0.34733642 0.43912382 0.12657231 0.33909079]
 [0.38971508 0.87083286 0.80172841 0.08342745 0.38680392 0.
  0.11970705 0.65855805 0.49531597 0.63248154]
 [0.50291385 0.89801615 0.86242035 0.19901899 0.34733642 0.11970705
  0.         0.69356514 0.46945713 0.5385183 ]
 [0.54813284 0.2153994  0.23524691 0.67999217 0.43912382 0.65855805
  0.69356514 0.         0.34977386 0.7156706 ]
 [0.61773847 0.496693   0.58158885 0.5554138  0.12657231 0.49531597
  0.46945713 0.34977

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = np.arange(10,dtype=np.float32)
x = x.astype(np.int32 ,copy = False)
print(x)


[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(9).reshape(3,3)
for ind, val in np.ndenumerate(x):
  print(ind, val)

for ind in np.ndindex(x.shape):
  print(ind, x[ind])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
a, b = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
c = np.sqrt(a*a+b*b)
sigma , mu = 1.0, 0.0
d = np.exp(-((c-mu)**2 / (2.0* sigma**2)))
print(d)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace = False),1)
print(x)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
z = np.random.rand(5,10)
x = z-z.mean(axis = 1, keepdims = True)
print(x)

[[-0.28407352  0.44598434  0.48550543 -0.2958746   0.18235674 -0.47746751
   0.17916933 -0.15341755 -0.30977431  0.22759164]
 [-0.21061943 -0.28932763  0.17354177 -0.0646671   0.44628424  0.38665907
  -0.24848304 -0.12149867  0.42025655 -0.49214577]
 [-0.07499408  0.33940735 -0.32303595  0.20921883  0.30506604 -0.22123344
   0.50208809 -0.34200389 -0.01264349 -0.38186946]
 [-0.0838666  -0.14977874  0.04591227  0.12342075 -0.06294483  0.17064059
  -0.2371131  -0.02231566  0.04865091  0.1673944 ]
 [-0.01675709  0.31044882  0.46851507 -0.45105723  0.3284902  -0.38810802
   0.10449392  0.27925473 -0.42922918 -0.20605122]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[6 4 6]
 [0 2 5]
 [8 4 8]]
[[0 2 5]
 [6 4 6]
 [8 4 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(0,1,10)
c = 0.5
v = x.flat[np.abs(x-c).argmin()]
print(v)

0.4703240646815817


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
i = np.nditer([a,b,None])
for x,y,z in i: z[...] = x + y
print(i.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def afinal(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
#x += np.bincount(y, minlength=len(x))
np.add.at(x,y,1)
print(x)

[2. 2. 3. 2. 5. 3. 4. 3. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a = [9,1,2,1,8,4]
b = [9,2,7,2,3,9]
F = np.bincount(b,a)
print(F)

[ 0.  0.  2.  8.  0.  0.  0.  2.  0. 13.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
a,b = 16,16
z = np.random.randint(0,2,(b,a,3)).astype(np.ubyte)

c = z[...,0]*(256*256) + z[...,1]*256 +z[...,2]
n = len(np.unique(c))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
x = np.random.randint(0,10,(2,5,2,5))
sum = x.sum(axis = (-2,-1))
print(sum)

[[58 30 49 58 38]
 [42 30 43 55 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
z = np.random.uniform(0,1,100)
x = np.random.randint(0,10,100)
zsums = np.bincount(x, weights=z)
zcounts = np.bincount(x)
zmeans = zsums / zcounts
print(zmeans)


[0.52625041 0.49456504 0.49437784 0.54621613 0.35798758 0.4197946
 0.43844243 0.66317691 0.56928977 0.68760367]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
x = np.random.uniform(0,1,(4,4))
y = np.random.uniform(0,1,(4,4))
np.diag(np.dot(x,y))

array([1.10392179, 1.04277349, 1.41671185, 1.0106405 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
x = np.array([9,8,7,6,5])
c = 3
x0 = np.zeros(len(x)+(len(x)-1)*c)
x0[::c+1] = x
print(x0)

[9. 0. 0. 0. 8. 0. 0. 0. 7. 0. 0. 0. 6. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
x = np.arange(36).reshape(6,6)
x[[0,1]]=x[[1,0]]
print(x)

[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
fac = np.random.randint(0,100,(10,3))
x = np.roll(fac.repeat(2,axis=1),-1,axis=1)
x = x.reshape(len(x)*3,2)
x = np.sort(x,axis=1)
v = x.view( dtype=[('p0',x.dtype),('p1',x.dtype)] )
v = np.unique(v)
print(v)

[( 3, 16) ( 3, 29) ( 3, 42) ( 3, 82) ( 4, 14) ( 4, 75) (14, 16) (14, 67)
 (14, 75) (16, 26) (16, 67) (16, 72) (16, 82) (18, 25) (18, 26) (25, 26)
 (26, 72) (29, 42) (41, 50) (41, 61) (42, 55) (42, 88) (44, 52) (44, 83)
 (50, 61) (50, 84) (50, 90) (52, 83) (55, 88) (84, 90)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
x = np.bincount([1,1,2,3,4,4,6])
y = np.repeat(np.arange(len(x)), x)
print(y)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def mavg(a, n=3) :
    t = np.cumsum(a, dtype=float)
    t[n:] = t[n:] - t[:-n]
    return t[n - 1:] / n
x = np.arange(20)
print(mavg(x, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def roll(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
z = roll(np.arange(10), 3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
x = np.random.randint(0,2,50)
np.logical_not(x, out = x)
x = np.random.uniform(-1.0,1.0,50)
np.negative(x,out=x)

array([ 0.70440493,  0.86019608,  0.14654842, -0.92048976, -0.41121736,
        0.11097707, -0.39975906,  0.71903292, -0.89595133,  0.81394627,
       -0.07696222,  0.82169447, -0.95086524,  0.89360313,  0.39931968,
        0.56642177,  0.95920838, -0.38582098, -0.83451318, -0.59576687,
        0.86580121,  0.98215402, -0.74054863,  0.45214656, -0.10756251,
        0.43642602,  0.29390027,  0.21088407, -0.22580266,  0.43761882,
       -0.13155193,  0.8309155 ,  0.14512725,  0.1654956 , -0.82203718,
        0.21496514, -0.7183888 , -0.95897289, -0.48817514, -0.33349263,
        0.09455516,  0.72889388,  0.08140063, -0.2504498 ,  0.50983261,
       -0.04773437, -0.63934726, -0.97838434, -0.36275575, -0.3412653 ])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[15.23047032  7.9370893   1.04158479  4.06216436  0.99697994  6.9418704
 13.88482616  3.08758519  3.20220564  2.32656212]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.66088009  4.19615177  3.07654035  1.64323782  5.35491658  2.89035972
   8.51781253  7.71066682  2.38187863  3.01545977]
 [ 1.66215894  5.8352075  10.62348981 12.50108869 10.94537595  7.52029333
   2.90847631 14.0348146  13.68596311 11.62106829]
 [11.94330131  7.17681824  0.20789488  0.25249634  5.51986028  5.84786419
  11.0245804   7.65080574  0.1224114   2.17176059]
 [12.15441247  1.59738884 12.6626871   3.1931642   6.6605618   1.98803486
   9.33495309  3.82430461  0.26720639  6.31749819]
 [15.41824318  5.45111052  4.64442672  5.05267952  2.67001877  4.73780731
  13.51116411  0.37877476  3.44260286  4.93441895]
 [10.06934683  6.26451932  0.40571869  1.77299603  7.45292748  4.79507366
   9.29232996  9.64529254  2.00815615  4.29108533]
 [14.7486222   9.44539405  1.35726553  3.00878928  3.84274307  8.23293321
  13.80946595  5.80930352  2.68253916  0.16173975]
 [ 7.10412712  2.0648794   4.59256017  4.13584083  6.79758131  0.65953631
   5.96615812  9.3082624   4.93702256  5.08298846]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 7 3 4 2 3 1 8 3 3]
 [8 9 0 0 2 4 7 9 3 7]
 [0 7 8 0 6 3 2 2 8 7]
 [4 1 6 7 2 9 5 3 5 1]
 [1 4 0 7 7 4 3 7 9 8]
 [9 6 2 9 5 7 0 7 6 5]
 [0 3 3 7 9 6 4 1 9 9]
 [1 2 8 2 8 0 3 6 9 2]
 [1 3 7 4 2 4 8 5 0 5]
 [9 3 9 4 5 3 0 0 7 2]]
[[0 0 0 0 0]
 [0 2 7 3 4]
 [0 8 9 0 0]
 [0 0 7 8 0]
 [0 4 1 6 7]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
x = np.arange(1,15,dtype=np.uint32)
z = stride_tricks.as_strided(x,(11,4),(4,4))
print(z)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
x = np.random.uniform(0,1,(10,10))
u,s,v = np.linalg.svd(x)
rank = np.sum(s>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
a = np.random.randint(0,10,100)
print(np.bincount(a).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
x = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
a = stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(a)

[[[[4 0 2]
   [0 2 3]
   [1 4 1]]

  [[0 2 0]
   [2 3 4]
   [4 1 0]]

  [[2 0 1]
   [3 4 3]
   [1 0 2]]

  [[0 1 1]
   [4 3 3]
   [0 2 4]]

  [[1 1 1]
   [3 3 1]
   [2 4 3]]

  [[1 1 1]
   [3 1 4]
   [4 3 1]]

  [[1 1 3]
   [1 4 3]
   [3 1 1]]

  [[1 3 0]
   [4 3 2]
   [1 1 1]]]


 [[[0 2 3]
   [1 4 1]
   [3 4 0]]

  [[2 3 4]
   [4 1 0]
   [4 0 1]]

  [[3 4 3]
   [1 0 2]
   [0 1 1]]

  [[4 3 3]
   [0 2 4]
   [1 1 3]]

  [[3 3 1]
   [2 4 3]
   [1 3 3]]

  [[3 1 4]
   [4 3 1]
   [3 3 4]]

  [[1 4 3]
   [3 1 1]
   [3 4 1]]

  [[4 3 2]
   [1 1 1]
   [4 1 4]]]


 [[[1 4 1]
   [3 4 0]
   [4 4 2]]

  [[4 1 0]
   [4 0 1]
   [4 2 2]]

  [[1 0 2]
   [0 1 1]
   [2 2 2]]

  [[0 2 4]
   [1 1 3]
   [2 2 2]]

  [[2 4 3]
   [1 3 3]
   [2 2 4]]

  [[4 3 1]
   [3 3 4]
   [2 4 1]]

  [[3 1 1]
   [3 4 1]
   [4 1 4]]

  [[1 1 1]
   [4 1 4]
   [1 4 3]]]


 [[[3 4 0]
   [4 4 2]
   [0 4 2]]

  [[4 0 1]
   [4 2 2]
   [4 2 4]]

  [[0 1 1]
   [2 2 2]
   [2 4 2]]

  [[1 1 3]
   [2 2 2]
   [4 2 3]]

  [[1 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class sym(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(sym, self).__setitem__((i,j), value)
        super(sym, self).__setitem__((j,i), value)

def symetric(x):
    return np.asarray(x + x.T - np.diag(x.diagonal())).view(sym)

c = symetric(np.random.randint(0,10,(5,5)))
c[2,3] = 42
print(c)

[[ 6 10 10  7 14]
 [10  3  8  2  5]
 [10  8  8 42 17]
 [ 7  2 42  8 14]
 [14  5 17 14  7]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p,n = 10,20
x = np.ones((p,n,n))
y = np.ones((p,n,1))
l = np.tensordot(x,y, axes = [[0,2],[0,1]])
print(l)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
z = np.ones((16,16))
k = 4
x = np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0], k), axis=0),
                                       np.arange(0, z.shape[1], k), axis=1)
print(x)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(40,40))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5
print(x[np.argsort(x)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cart(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    cx = np.indices(shape, dtype=int)
    cx = cx.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        cx[:, n] = arrays[n][cx[:, n]]

    return cx

print (cart(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
x = np.array([("hello",1.6,2),
              ("J",4.8,6)])
c = np.core.records.fromarrays(x.T,
                               names = 'col1,col2,col3',
                               formats = 'S8, f8, i8')
print(c)

[(b'hello', 1.6, 2) (b'J', 4.8, 6)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.randint(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->ii',x,x,x)

The slowest run took 24.53 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.27 µs per loop
The slowest run took 13.17 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 5: 133 ns per loop


ValueError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
x = np.random.randint(0,5,(8,3))
y = np.random.randint(0,5,(2,2))

z = (x[..., np.newaxis, np.newaxis] == y)
rows = np.where(z.any((3,1)).all(1))[0]
print(rows)

[0 2 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
x = np.random.randint(0,5,(10,3))
print(x)
c = np.all(x[:,1:]==x[:,:-1], axis = 1)
d = x[~c]
print(d)

[[1 3 3]
 [0 0 1]
 [2 4 4]
 [2 1 4]
 [3 0 3]
 [4 1 4]
 [4 3 3]
 [0 2 4]
 [0 0 2]
 [3 0 4]]
[[1 3 3]
 [0 0 1]
 [2 4 4]
 [2 1 4]
 [3 0 3]
 [4 1 4]
 [4 3 3]
 [0 2 4]
 [0 0 2]
 [3 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
z = np.array([0,1,2,4,16,32,64,128,7,9,13], dtype = np.uint8)
print(np.unpackbits(z[:, np.newaxis],axis = 1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
x = np.random.randint(0,2,(9,4))
a = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, id = np.unique(a, return_index = True)
v = x[id]
print(v)

[[0 0 0 0]
 [0 0 0 1]
 [0 1 1 1]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.14347476, 0.07316486, 0.09558327, 0.04666386, 0.13220521],
       [0.54158352, 0.27618015, 0.36080438, 0.1761451 , 0.49904359],
       [0.46864456, 0.23898498, 0.31221225, 0.15242237, 0.43183379],
       [0.07182884, 0.03662907, 0.04785256, 0.02336167, 0.06618687],
       [0.48871369, 0.24921922, 0.32558235, 0.15894967, 0.45032654]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**0.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
c = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
z = np.logical_and.reduce(np.mod(c, 1) == 0, axis=-1)
z &= (c.sum(axis=-1) == n)
print(c[z])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
a = np.random.randn(100)
n = 1000
x = np.random.randint(0,a.size,(n, a.size))
mn = a[x].mean(axis=1)
con = np.percentile(mn, [2.5, 97.5])
print(con)

[-0.27649796  0.06947701]
